#!/usr/bin/env bash
# transfer_file.sh
# Usage: transfer_file.sh PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

# Check if the correct number of arguments is provided
if [ "$#" -ne 4 ]; then
	echo "Usage: transfer_file.sh PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# Use SCP to transfer the file to the specified user and IP using the provided SSH key
	scp -i "$4" "$1" "$3@$2":~/
fi
