#!/usr/bin/env bash
# transfer_file.sh
# Usage: transfer_file.sh PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

# Check if the correct number of arguments is provided
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	# Use SCP to transfer the file to the specified user and IP using the provided SSH key
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
