#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

ADD301_REDIRECT=$'\trewrite ^/redirect_me https://animepahe.ru/anime/40680913-4836-eb87-209a-80a53d8bdb94 permanent;'

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Find the correct line number dynamically
LINE_NUMBER=$(grep -n 'server {' /etc/nginx/sites-available/default | cut -d: -f1)
# Insert the redirection directive
sudo sed -i "${LINE_NUMBER}a $ADD301_REDIRECT" /etc/nginx/sites-available/default

sudo service nginx restart
