#!/usr/bin/env bash
#prints diffent PIDs for differnt processes.
#echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | grep -v grep | head -50
