#!/usr/bin/env bash
#This script prints "Best School" 10 times and "Hi" the 9th time.
count=0
while [ $count -le 9 ]
do
	echo "Best School"
	if [ $count == 8 ]
	then
		echo "Hi"
	fi
	count=$(( count + 1 ))
done
