#!/usr/bin/env bash
#This scripts prints best school 10 times but chages up on 4 and 8
count=0
while [ $count -le 9 ]
do
	if [ $count == 3 ]
	then
		echo "bad luck"
	elif [ $count == 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$(( count + 1 ))
done
