#!/usr/bin/env bash
#This script prints numbers 1 to 20 and raises superstitious numbers.
count=1
while [ $count -le 20 ]
do
	echo "$count"
	case $count in 4)
	echo "bad luck from China";;
	9)
	echo "bad luch from Japan";;
	17)
	echo "bad luck from Itally";;
	esac
	count=$(( count + 1 ))
done
